version: '3'
services:
  location-tracker:
    build: .
    ports:
      - "4001:4001"
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/location_db?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=location_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
